const courses=[
{id:1,title:'从零构建高级感 UI 设计',category:'设计创意',instructor:'林墨 · 资深产品设计师',price:269,originalPrice:399,rating:4.9,students:3286,lessons:36,duration:'12.5 小时',level:'进阶',tag:'畅销课程',art:'art-ui',color:'#b8c5bd',description:'从版式、色彩到组件系统，掌握可落地的界面设计方法，并完成一套完整的商业产品设计。',includes:['36 节高清视频课程','6 个实战设计项目','源文件与设计模板','课程社群与作业点评']},
{id:2,title:'手机摄影：日常也能拍出故事感',category:'影像摄影',instructor:'周屿 · 纪实摄影师',price:159,originalPrice:229,rating:4.8,students:5120,lessons:28,duration:'8.2 小时',level:'入门',tag:'口碑精选',art:'art-photo',color:'#d3c4a9',description:'无需昂贵器材，用手机掌握光线、构图和叙事，让普通生活成为有温度的影像作品。',includes:['28 节场景化课程','12 个拍摄任务','调色预设与参数表','优秀作品长期更新']},
{id:3,title:'数据分析思维与商业实战',category:'商业增长',instructor:'陈序 · 商业分析顾问',price:329,originalPrice:469,rating:4.9,students:2468,lessons:42,duration:'16.8 小时',level:'进阶',tag:'编辑推荐',art:'art-data',color:'#d8b66a',description:'摆脱工具堆砌，从业务问题出发建立分析框架，用数据支持判断、表达洞察并推动决策。',includes:['42 节系统课程','8 个真实商业案例','分析框架与表格模板','结课项目导师点评']},
{id:4,title:'写作力：打造有影响力的内容',category:'内容表达',instructor:'许言 · 品牌内容主理人',price:199,originalPrice:299,rating:4.7,students:4389,lessons:31,duration:'9.6 小时',level:'通用',tag:'近期上新',art:'art-write',color:'#c7af9d',description:'从选题、结构到语言节奏，系统拆解优质内容的生产过程，写出清晰、有力、有记忆点的表达。',includes:['31 节核心课程','20 个写作练习','选题库与结构模板','社群共写与案例拆解']},
{id:5,title:'前端开发：从页面到完整产品',category:'职场技能',instructor:'顾川 · 全栈工程师',price:399,originalPrice:599,rating:4.9,students:1897,lessons:56,duration:'25.4 小时',level:'系统课',tag:'高含金量',art:'art-code',color:'#8fa89b',description:'以真实产品为主线，掌握 HTML、CSS、JavaScript 与工程化思维，独立完成可上线的 Web 应用。',includes:['56 节高清课程','3 个完整产品项目','全部项目源码','代码评审与答疑社群']},
{id:6,title:'个人品牌与商业化增长',category:'商业增长',instructor:'沈一 · 品牌策略顾问',price:299,originalPrice:429,rating:4.8,students:3021,lessons:38,duration:'13.7 小时',level:'进阶',tag:'热门路径',art:'art-business',color:'#b7c09d',description:'定位你的独特价值，搭建稳定的内容与产品体系，让专业能力获得持续、健康的商业回报。',includes:['38 节策略课程','个人品牌定位画布','产品设计与定价模板','10 个增长案例拆解']}
];
const $=s=>document.querySelector(s),money=n=>`¥${n.toFixed(0)}`,art=c=>`<div class="cover-art ${c.art}"><i></i><i></i><i></i></div>`;
const state={category:'全部',search:'',sort:'popular',cart:JSON.parse(localStorage.getItem('zhiyu-cart')||'[]'),favorites:JSON.parse(localStorage.getItem('zhiyu-favorites')||'[]'),coupon:null};
const categories=['全部',...new Set(courses.map(c=>c.category))],grid=$('#courseGrid');let toastTimer;
function save(){localStorage.setItem('zhiyu-cart',JSON.stringify(state.cart));localStorage.setItem('zhiyu-favorites',JSON.stringify(state.favorites))}
function counts(){$('#cartCount').textContent=state.cart.length;$('#favoriteCount').textContent=state.favorites.length}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2200)}
function renderCategories(){$('#categoryTabs').innerHTML=categories.map(c=>`<button class="${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('')}
function list(){let k=state.search.trim().toLowerCase(),a=courses.filter(c=>(state.category==='全部'||c.category===state.category)&&(!k||`${c.title}${c.instructor}${c.category}`.toLowerCase().includes(k)));return a.sort((x,y)=>state.sort==='rating'?y.rating-x.rating:state.sort==='priceAsc'?x.price-y.price:state.sort==='priceDesc'?y.price-x.price:y.students-x.students)}
function card(c){let fav=state.favorites.includes(c.id);return `<article class="course-card" data-id="${c.id}"><div class="course-cover" style="background:${c.color}"><span class="cover-tag">${c.tag}</span><button class="favorite-course ${fav?'active':''}" data-favorite="${c.id}">${fav?'♥':'♡'}</button>${art(c)}</div><div class="course-info"><div class="course-meta"><span>${c.category}</span><span>${c.lessons} LESSONS · ${c.level}</span></div><h3>${c.title}</h3><p>${c.instructor}</p><div class="course-bottom"><div class="rating">★ ${c.rating}<span>(${c.students.toLocaleString()} 人学习)</span></div><div class="price"><strong>${money(c.price)}</strong><del>${money(c.originalPrice)}</del><button class="add-course" data-add="${c.id}">+</button></div></div></div></article>`}
function renderCourses(){let a=list();grid.innerHTML=a.map(card).join('');$('#emptyState').classList.toggle('hidden',a.length>0)}
function add(id){if(state.cart.includes(id))return toast('这门课程已经在购物袋中');state.cart.push(id);save();counts();renderCart();toast('已加入购物袋')}
function favorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();counts();renderCourses();toast(state.favorites.includes(id)?'已收藏课程':'已取消收藏')}
function totals(){let subtotal=state.cart.reduce((s,id)=>s+courses.find(c=>c.id===id).price,0),discount=state.coupon==='NEW10'?Math.round(subtotal*.1):state.coupon==='STUDY30'&&subtotal>=299?30:0;return{subtotal,discount,total:subtotal-discount}}
function renderCart(){let a=state.cart.map(id=>courses.find(c=>c.id===id)).filter(Boolean),box=$('#cartItems');if(!a.length){box.innerHTML='<div class="empty-cart"><i>◌</i><strong>购物袋还是空的</strong><span>去挑一门感兴趣的课程吧</span></div>';$('#cartFooter').classList.add('hidden');return}$('#cartFooter').classList.remove('hidden');box.innerHTML=a.map(c=>`<div class="cart-item"><div class="cart-thumb" style="background:${c.color}">${art(c)}</div><div class="cart-item-info"><small>${c.category}</small><strong>${c.title}</strong><span>${money(c.price)}</span></div><button class="remove-item" data-remove="${c.id}">×</button></div>`).join('');let t=totals();$('#subtotal').textContent=money(t.subtotal);$('#discount').textContent=`-${money(t.discount)}`;$('#discountLine').classList.toggle('hidden',!t.discount);$('#totalPrice').textContent=money(t.total)}
function openCart(){$('#cartDrawer').classList.add('open');$('#drawerOverlay').classList.add('open');document.body.style.overflow='hidden'}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#drawerOverlay').classList.remove('open');document.body.style.overflow=''}
function openCourse(id){let c=courses.find(x=>x.id===id);$('#courseModal').innerHTML=`<button class="modal-close" data-close-modal>×</button><div class="course-modal-inner"><div class="modal-cover" style="background:${c.color}">${art(c)}</div><div class="modal-content"><span class="section-kicker">${c.category} · ${c.level}</span><h2>${c.title}</h2><p class="instructor">${c.instructor}</p><p class="description">${c.description}</p><div class="course-stats"><div><strong>${c.lessons} 节</strong><span>课程内容</span></div><div><strong>${c.duration}</strong><span>总时长</span></div><div><strong>${c.rating} 分</strong><span>学员评价</span></div></div><ul class="includes">${c.includes.map(x=>`<li>${x}</li>`).join('')}</ul><div class="modal-buy"><div class="modal-price"><strong>${money(c.price)}</strong><del>${money(c.originalPrice)}</del></div><button class="primary-button" data-modal-add="${c.id}">加入购物袋 <span>→</span></button></div></div></div>`;$('#modalOverlay').classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){$('#modalOverlay').classList.remove('open');document.body.style.overflow=''}
function checkout(){if(!state.cart.length)return;closeCart();let t=totals();$('#checkoutSummary').innerHTML=`<div class="price-line"><span>${state.cart.length} 门课程</span><strong>${money(t.subtotal)}</strong></div>${t.discount?`<div class="price-line discount-line"><span>优惠金额</span><strong>-${money(t.discount)}</strong></div>`:''}<div class="price-line"><span>应付金额</span><strong>${money(t.total)}</strong></div>`;$('#payAmount').textContent=money(t.total);$('#checkoutOverlay').classList.add('open');document.body.style.overflow='hidden'}
function closeCheckout(){$('#checkoutOverlay').classList.remove('open');document.body.style.overflow=''}
$('#categoryTabs').onclick=e=>{let b=e.target.closest('[data-category]');if(b){state.category=b.dataset.category;renderCategories();renderCourses()}};
grid.onclick=e=>{let f=e.target.closest('[data-favorite]'),a=e.target.closest('[data-add]'),c=e.target.closest('.course-card');if(f){e.stopPropagation();favorite(+f.dataset.favorite)}else if(a){e.stopPropagation();add(+a.dataset.add)}else if(c)openCourse(+c.dataset.id)};
$('#searchInput').oninput=e=>{state.search=e.target.value;renderCourses()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderCourses()};$('#resetFilters').onclick=()=>{state.category='全部';state.search='';$('#searchInput').value='';renderCategories();renderCourses()};
$('#cartButton').onclick=openCart;$('#closeCart').onclick=closeCart;$('#drawerOverlay').onclick=closeCart;$('#cartItems').onclick=e=>{let b=e.target.closest('[data-remove]');if(b){state.cart=state.cart.filter(x=>x!==+b.dataset.remove);state.coupon=null;save();counts();renderCart();toast('已移出购物袋')}};
$('#applyCoupon').onclick=()=>{let c=$('#couponInput').value.trim().toUpperCase();if(!['STUDY30','NEW10'].includes(c))return toast('优惠码无效，请重新输入');if(c==='STUDY30'&&totals().subtotal<299)return toast('满 299 元可使用该优惠码');state.coupon=c;renderCart();toast('优惠码已生效')};
$('#checkoutButton').onclick=checkout;$('#closeCheckout').onclick=closeCheckout;$('#checkoutOverlay').onclick=e=>{if(e.target===$('#checkoutOverlay'))closeCheckout()};
document.querySelectorAll('.payment-methods label').forEach(x=>x.onclick=()=>{document.querySelectorAll('.payment-methods label').forEach(y=>y.classList.remove('selected'));x.classList.add('selected')});
$('#payButton').onclick=()=>{if(!$('#agreement').checked)return toast('请先同意课程购买协议');let b=$('#payButton');b.textContent='正在创建订单…';b.disabled=true;setTimeout(()=>{let n=`ZY${Date.now().toString().slice(-10)}`;state.cart=[];state.coupon=null;save();counts();renderCart();closeCheckout();b.disabled=false;b.innerHTML='确认支付 <span id="payAmount">¥0</span>';toast(`订单 ${n} 已创建，课程已加入学习中心`)},1000)};
$('#modalOverlay').onclick=e=>{if(e.target===$('#modalOverlay')||e.target.closest('[data-close-modal]'))closeModal();let b=e.target.closest('[data-modal-add]');if(b){add(+b.dataset.modalAdd);closeModal();openCart()}};
$('#favoriteButton').onclick=()=>{if(!state.favorites.length)return toast('暂时还没有收藏课程');grid.innerHTML=courses.filter(c=>state.favorites.includes(c.id)).map(card).join('');$('#courses').scrollIntoView({behavior:'smooth'});toast('已显示收藏课程')};
$('#profileButton').onclick=e=>{e.stopPropagation();$('#profilePopover').classList.toggle('hidden')};document.onclick=e=>{if(!e.target.closest('#profilePopover'))$('#profilePopover').classList.add('hidden')};$('#ordersButton').onclick=()=>toast('暂无待处理订单');$('#mobileMenu').onclick=()=>$('#mainNav').classList.toggle('open');
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));document.querySelectorAll('.path-list [data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCategories();renderCourses();$('#courses').scrollIntoView({behavior:'smooth'})});
$('#subscribeForm').onsubmit=e=>{e.preventDefault();e.currentTarget.reset();toast('订阅成功，欢迎加入知屿周刊')};document.onkeydown=e=>{if(e.key==='Escape'){closeCart();closeModal();closeCheckout()}};
renderCategories();renderCourses();renderCart();counts();
